var str = `BLANDIN, JOHN J., LIEUTENANT, J.G. 
BLOW, GEORGE P., LIEUTENANT, J.G.
     BOYD, DAVID F.JR., NAVAL CADET 
         BOWERS, FREDERIC C., PASSED ASSISTANT ENGINEER 
             BRONSON, AMON, NAVAL CADET 
                 CATLIN, ALBERTUS W., MARINE, FIRST LIEUTENANT 
                     CHIDWICK, JOHN P., CHAPLAIN
                         CLUVERIUS, WATT T., NAVAL CADET 
                             CRENSHAW, ARTHUR, NAVAL CADET, ENGINEERING DIVISION 
                                 HELMS, GEORGE, CARPENTER
                                 HENEBERGER, LUCIEN G., SURGEON
                                     HILL, JOSEPH, GUNNER
                                     HOLDEN, JONAS H., NAVAL CADET 
                                         HOLMAN, GEORGE F.W., LIEUTENANT
                                             HOOD, JOHN, LIEUTENANT
                                             HOWELL, CHARLES P., CHIEF ENGINEER 
JENKINS, FRIEND W., LIEUTENANT
     JUNGEN, CARL W., LIEUTENANT
         LARKIN, FRANCIS E., BOATSWAIN
             MCCARTY, B., PAY CLERK 
MERRITT, DARWIN R., ASSISTANT ENGINEER 
     MORRIS, JOHN R., ASSISTANT ENGINEER 
         RAY, CHARLES M., PAYMASTER
             SIGSBEE, CHARLES D., CAPTAIN COMMANDING VESSEL 
                 WAINWRIGHT, RICHARD, LIEUTENANT COMMANDER 
                     WASHINGTON, POPE, NAVAL CADET, ENGINEERING DIVSION
ENLISTED MEN
ADAMS, JOHN T., COAL PASSER 
AITKEN, JAMES P., BOATSWAIN'S MATE, FIRST CLASS 
     ALLEN, JAMES W., MESS ATTENDANT 
ANDERSEN, HOLM A., COAL PASSER 
ANDERSON, AXEL C., SEAMAN
ANDERSON, CHARLES, LANDSMAN
ANDERSON, JOHN, BOATSWAIN'S MATE, SECOND CLASS 
ANDERSON, GUSTAV A., SEAMAN
     ANDERSON, OSKAR, COCKSWAIN
ANDREWS, FRANK, ORDINARY SEAMAN 
ANFINDSEN, ABRAHAM, COXSWAIN
     ANTHONY, WILLIAM, MARINE PRIVATE 
ANGLUNG, BERNHARD, BLACKSMITH
AUCHENBACH, HARRY, FIREMAN, SECOND CLASS 
     AWO, FIRSANION, STEERAGE COOK 
BARRY, JOHN P., APPRENTICE, FIRST CLASS 
BARRY, LEWIS L., COAL PASSER 
BAUM, HENRY S., LANDSMAN
BECKER, JAKOB, CHIEF MACHINIST 
BELL, JOHN R., CABIN STEWARD 
BENNETT, JOHN, MARINE PRIVATE 
     BLOOMER, JOHN H., LANDSMAN
BOOKBINDER, JOHN, APPRENTICE, SECOND CLASS 
BOLL, FRITZ, BAYMAN
BONNER, LEON, SEAMAN
BOTTING, VINCENT H., MARINE PRIVATE 
BOYLE, JAMES, QUARTERMASTER, FIRST CLASS 
BRINKMAN, HEINRICH, SEAMAN
BROFELDT, ARTHUR, CHIEF GUNNER'S MATE 
BROSNAN, GEORGE, MARINE PRIVATE 
BROWN, JAMES T., MARINE SERGEANT 
BRUNS, ADOLF C., QUARTERMASTER, THIRD CLASS 
     BULLOCK, CHARLES H., GUNNER'S MATE, SECOND CLASS 
BURKHARDT, ROBERT, QUARTERMASTER, SECOND CLASS 
BURNS, EDWARD, COAL PASSER 
BURNS, JAMES R., MARINE PRIVATE 
BUTLER, FREDERICK F., MACHINIST, SECOND CLASS 
     CAHILL, FRANCIS D., LANDSMAN
CAINE, THOMAS, BLACKSMITH
CAMERON, WALTER, SEAMAN
CARR HERBERT M., GUNNER'S MATE, SECOND CLASS 
CAULFIELD, WILLIAM R.B., LANDSMAN
CHINGI, SUKE, MESS ATTENDANT 
CHRISTIANSEN, CHARLES A., FIREMAN, FIRST CLASS 
     CHRISTIANSEN, KARL, FIREMAN, FIRST CLASS 
CLARK, THOMAS, COAL PASSER 
CLARKE, JAMES C., SHIPWRIGHT
COCHRANE, MICHAEL, FIREMAN, FIRST CLASS 
     COFFEY, JOHN, MARINE PRIVATE 
COLE, THOMAS M., BAYMAN
COLEMAN, WILLIAM, ORDINARY SEAMAN 
COLEMAN, WILLIAM, FIREMAN, SECOND CLASS 
CONROY, ANTHONY, COAL PASSER 
COSGROVE, WILLIAM, FIREMAN, SECOND CLASS 
     CRONIN, DANIEL, LANDSMAN
CURRAN, CHARLES, COCKSWAIN
DAHLMAN, BERGER, SEAMAN
     DAVID, GEORGE, ORDINARY SEAMAN 
DENNIG, CHARLES, SEAMAN
DIERKING, JOHN H., MARINE DRUMMER 
     DOLAN, JOHN, SEAMAN
DONOUGHY WILLIAM, ORDINARY SEAMAN 
DOWNING, MICHAEL J., MARINE PRIVATE 
     DRESSLER, GUSTAV J., APPRENTICE, FIRST CLASS 
DRURY, JAMES, FIREMAN, FIRST CLASS 
     DURCKIN, THOMAS J., ORDINARY SEAMAN 
EDLER, GEORGE, SEAMAN
EIERMANN, CHARLES F.W., GUNNER'S MATE FIRST CLASS 
     ERIKSON, ANDREW V., SEAMAN
ETTS, JOHN P., SEAMAN
EVENSEN, KARL, SEAMAN
FADDE, CHARLES F.J., APPRENTICE, FIRST CLASS 
FALK, RUDOLPH, OILER
FAUBEL, GEORGE D., CHIEF MACHINIST 
FEWER, WILLIAM J., BOATSWAIN'S MATE, SECOND CLASS 
FINCH, TRUBIE, APPRENTICE, FIRST CLASS 
FISHER, ALFRED J., OILER
     FISHER, FRANK, ORDINARY SEAMAN 
FLAHERTY, MICHAEL, FIREMAN, FIRST CLASS 
FLEISHMAN, LEWIS M., SEAMAN
     FLYNN, MICHAEL, SEAMAN
FLYNN, PATRICK, FIREMAN, SECOND CLASS 
     FOLEY, PATRICK J., APPRENTICE, FIRST CLASS 
FOUGERE, JOHN, COAL PASSER 
FOUNTAIN, BARTLEY, BOATSWAIN'S MATE, FIRST CLASS 
     FOX, GEORGE, LANDSMAN
FRANK, CHARLES, APPRENTICE, FIRST CLASS 
FURLONG, JAMES F., COAL PASSER 
GAFFNEY, PATRICK, FIREMAN, FIRST CLASS 
     GALPIN, C.P., MARINE PRIVATE 
GARDNER, FRANK, COAL PASSER 
GARDNER, THOMAS J., CHIEF YEOMAN 
     GARTRELL, WILLIAM M., FIREMAN, FIRST CLASS 
         GERMOND, C.V., MARINE PRIVATE 
GORDON, JOSEPH F., FIREMAN, FIRST CLASS 
GORMAN, WILLIAM H., ORDINARY SEAMAN 
GRADY, PATRICK, COAL PASSER 
GRAHAM, EDWARD P., COAL PASSER 
GRAHAM, JAMES A., CHIEF YEOMAN 
GREER, WILLIAM A., APPRENTICE, FIRST CLASS 
GRIFFIN, MICHAEL, FIREMAN, SECOND CLASS 
GROSS, HENRY, LANDSMAN
GRUPP, REINHARDT, COAL PASSER 
     HALLBERG, ALFRED, COCKSWAIN
HALLBERG, JOHN A., OILER
     HAM, AMBROSE, APPRENTICE, FIRST CLASS 
HAMBURGER, WILLIAM, LANDSMAN
HAMILTON, CHARLES A., APPRENTICE, FIRST CLASS 
HAMILTON, JOHN, CHIEF CARPENTER'S MATE 
HANRAHAN, WILLIAM C., COCKSWAIN
HARLEY, DANIEL O.C., FIREMAN, SECOND CLASS 
HARRIS, EDWARD, WATER TENDER 
HARRIS, MILLARD F., QUARTERMASTER, THIRD CLASS 
     HARRIS, WESTMORE, MESS ATTENDANT 
HARTY, THOMAS J., COAL PASSER 
HASSELL, CHARLES F., GUNNER'S MATE, THIRD CLASS 
HAUCK, CHARLES, LANDSMAN
HAWKINS, HOWARD B., ORDINARY SEAMAN 
     HEFFRON, JOHN, ORDINARY SEAMAN 
HENNEKES, ALBERT B., GUNNER'S MATE, SECOND CLASS 
     HERBERT, JOHN, LANDSMAN
     HERNESS, ALFRED B., GUNNER'S MATE, THIRD CLASS 
HERRIMAN, BENJAMIN H., APPRENTICE, FIRST CLASS 
     HOLLAND, ALFRED J., COCKSWAIN
HOLM, GUSTAV, BOATSWAIN'S MATE, SECOND CLASS 
     HOLZER, FREDERICK C., ORDINARY SEAMAN 
HORN, WILLIAM J., FIREMAN, FIRST CLASS 
HOUGH, WILLIAM L., LANDSMAN
HUGHES, PATRICK, FIREMAN, FIRST CLASS 
     HUTCHINGS, ROBERT, LANDSMAN
ISHIDA, OTOGIRO, STEERAGE COOK 
     JECTSON, HARRY, SEAMAN
JENCKS, CARLTON, GUNNER'S MATE, THIRD CLASS 
JERNEE, FRED, COAL PASSER 
JOHANSEN, PETER, C., SEAMAN
     JOHNSON, ALFRED, SEAMAN
JOHNSON, CHARLES, ORDINARY SEAMAN 
JOHNSON, CHARLES E., MARINE PRIVATE 
JOHNSON, GEORGE, COAL PASSER 
JOHNSON, JOHN W., LANDSMAN
JOHNSSON, PETER, OILER
JONES, THOMAS J., COAL PASSER 
JORDAN, WILLIAM J., MARINE PRIVATE 
JUST, CHARLES F., APPRENTICE, FIRST CLASS 
     KANE, JOSEPH H., LANDSMAN
KANE, MICHAEL, COAL PASSER 
KAY, JOHN A., MACHINIST, FIRST CLASS 
KEAN, EDWARD P., MARINE PRIVATE 
KELLY, HUGH, COAL PASSER 
KELLY, FRANK, MARINE PRIVATE 
KELLY, JOHN, COAL PASSER 
KESKULL, ALEXANDER, SEAMAN
KEYS, HARRY J., ORDINARY SEAMAN 
KIHLSTROM, FRITZ, ORDINARY SEAMAN 
KINSELLA, THOMAS F., MACHINIST, SECOND CLASS 
KINSEY, FREDERICK E., MACHINIST, SECOND CLASS 
KITAGATA, YUKICHI, WARRANT OFFICERS' COOK 
KNIESE, FREDERICK H., MACHINIST, FIRST CLASS 
     KOEBLER, GEORGE W., APPRENTICE, FIRST CLASS 
KRANYAK, CHARLES, APPRENTICE, FIRST CLASS 
KRUSE, HUGO, PAINTER
     KUSHIDA, KATSUSABURO, WARRANT OFFICER'S STEWARD 
LAIRD, CHARLES, MASTER - AT - ARMS, THIRD CLASS 
LAMBERT, WILLIAM, FIREMAN, SECOND CLASS 
     LANAHAN, MICHAEL, LANDSMAN
LANCASTER, LUTHER, BOATSWAIN'S MATE, SECOND CLASS 
LAPIERRE, GEORGE, APPRENTICE, FIRST CLASS 
     LARSEN, MARTIN, SEAMAN
     LARSEN, PEDER, SEAMAN
LAURIETTE, GEORGE M., MARINE PRIVATE 
LAWLER, EDWARD, COAL PASSER 
LEAGUE, JAMES M., CHIEF YEOMAN 
LEE, WILLIAM J., APPRENTICE, FIRST CLASS 
LEENE, DANIEL, COAL PASSER 
LEES, SAMUEL, ORDINARY SEAMAN 
LEUPOLD, GUSTAV.FIREMAN, SECOND CLASS 
LEWIS, DANIEL, OILER
LEWIS, JOHN B., WATER TENDER 
LIEBER, GEORGE, APPRENTICE, FIRST CLASS 
     LOAD, JOHN B., MASTER - AT - ARMS, THIRD CLASS 
         LOFTUS, PAUL, MARINE PRIVATE 
             LOHMAN, CHARLES A., COAL PASSER 
LORENZEN, JORGEN J., OILER
LOSKO, PETER A., MARINE PRIVATE 
LOUDEN, JAMES, W., APPRENTICE, SECOND CLASS 
LOWELL, CLARENCE E., ORDINARY SEAMAN 
LUND, WILLIAM, COCKSWAIN
     LUTZ, JOSEPH, MARINE PRIVATE 
LYDON, JOHN T., ORDINARY SEAMAN 
LYNCH, BERNARD, FIREMAN, FIRST CLASS 
LYNCH, MATTHEW, COAL PASSER 
     MACK, THOMAS, LANDSMAN
MALONE, MICHAEL, FIREMAN, SECOND CLASS 
MARSDEN, BENJAMIN L., APPRENTICE, FIRST CLASS 
MARSHALL, JOHN E., LANDSMAN
MARTENSSON, JOHAN, GUNNER'S MATE, THIRD CLASS 
MASON, JAMES H., LANDSMAN
MATIASEN, CARL, SEAMAN
     MATTISEN, WILLIAM, ORDINARY SEAMAN 
         MATTSEN, EDWARD, ORDINARY SEAMAN 
MATZA, JOHN, COAL PASSER 
     MCCANN, HARRY, SEAMAN
MCDERMOTT, JOHN, MARINE PRIVATE 
     MCDEVITT, WILLIAM, MARINE PRIVATE 
MCGONIGLE, HUGH, FIREMAN, SECOND CLASS 
     MCGUINNESS, WILLIAM, MARINE PRIVATE 
         MCKAY, EDWARD, MARINE PRIVATE 
MCMANUS, JOHN J., FIREMAN, SECOND CLASS 
     MCNAIR, WILLIAM, ORDINARY SEAMAN 
MCNIECE, FRANCIS J., COAL PASSER 
     MEEHAN, MICHAEL, MARINE SERGEANT 
MEILSTRUP, ELMER M., ORDINARY SEAMAN 
     MELVILLE, THOMAS, COAL PASSER 
MERZ, JOHN, LANDSMAN
MERO, ELDON H., CHIEF MACHINIST 
     MIKKELSEN, PETER, SEAMAN
MILLER, GEORGE, SEAMAN
MILLER, WILLIAM S., APPRENTICE, SECOND CLASS 
MOBLES, GEORGE, COCKSWAIN
MOORE, EDWARD H., COAL PASSER 
MONAHAN, JOSEPH P., MARINE PRIVATE 
MONFORT.WILLIAM, LANDSMAN
     MORINIERE, LOUIS, SEAMAN
MOSS, GERHARD C., MACHINIST, FIRST CLASS 
MOSS, JON H., LANDSMAN
MUDD, NOBLE T., SEAMAN
MURPHY, CORNELIUS, OILER
NAGAMINE, TOMEKICHI, MESS ATTENDANT 
NIELSEN, SOPHUS, COCKSWAIN
NEILSEN, JOHN C., SEAMAN
NEWMAN, F.J., MARINE PRIVATE 
NEWTON, C.H., MARINE FIFER 
NOBLE, WILLIAM, FIREMAN, SECOND CLASS 
NOLAN, CHARLES M., GUNNER'S MATE, THIRD CLASS 
O'CONNOR, JAMES, CHIEF BOATSWAIN'S MATE 
O'HAGAN, THOMAS J., APPRENTICE, FIRST CLASS 
OHYE, MAS, MESS ATTENDANT 
O'NEILL, PATRICK, FIREMAN, SECOND CLASS 
ORDING, GUSTAV C., CARPETER'S MATE, THIRD CLASS 
O'REGAN, HENRY H., WATER TENDER 
PAIGE, FREDERICK, LANDSMAN
PALMGREN, JOHN, SEAMAN
     PANCK, JOHN H., FIREMAN, FIRST CLASS 
PERRY, ROBERT, MESS ATTENDANT 
PHILLIPS, FRANCIS C., APPRENTICE, FIRST CLASS 
     PILCHER, CHARLES F., ORDINARY SEAMAN 
PINKNEY, JAMES, MESS ATTEDNANT 
PORTER, JOHN, COAL PASSER 
POWERS, JOHN, OILER
PRICE, DANIEL, FIREMAN, FIRST CLASS 
QUIGLEY, THOMAS J., PLUMBER AND FITTER 
QUINN, CHARLES P., OILER
     RAU, ARTHUR, SEAMAN
     REDEN, MARTIN, SEAMAN
REILLY, JOSEPH, FIREMAN, FIRST CLASS 
     RICHARDS, WALTER E., APPRENTICE, SECOND CLASS 
RICHTER, A.H., MARINE CORPORAL 
RIEGER, WILLIAM A., GUNNER'S MATE, FIRST CLASS 
RISING, NEWELL, COAL PASSER 
ROBERTS, JAMES H., MARINE PRIVATE 
ROBINSON, WILLIAM, LANDSMAN
ROOS, PETER, SAILMAKER
     ROWE, JAMES, SHIP'S COOK, FOURTH CLASS 
         RUSCH, FRANK, ORDINARY SEAMAN 
RUSHWAORTH, WILLIAM, CHIEF MACHINIST 
SAFFORD, CLARENCE E., GUNNER'S MATE, FIRST CLASS 
SALMIN, MICHAEL E., ORDINARY SEAMAN 
SCHOEN, JOSEPH, MARINE CORPORAL 
SCHROEDER, AUGUST, ORDINARY SEAMAN 
     SCHWARTZ, GEORGE, SHIP'S COOK, FIRST CLASS 
SCOTT, CHARLES A., CARPENTER'S MATE, SECOND CLASS 
SCULLY, JOSEPH, BOILER MAKER 
SEERY, JOSEPH, FIREMAN, FIRST CLASS 
SELLERS, WALTER S., APOTHECARY
     SHEA, JEREMIAH, COAL PASSER 
SHEA, JOHN J., COAL PASSER 
SHEA, PATRICK J., FIREMAN, FIRST CLASS 
SHEA, THOMAS, LANDSMAN
SHERIDAN, OWEN, FIREMAN, SECOND CLASS 
SHILLINGTON, JOHN H., YEOMAN, THIRD CLASS 
SIMMONS, ALFRED, COAL PASSER 
     SMITH, CARL A., SEAMAN
SMITH NICHOLAS J., APPRENTICE, FIRST CLASS 
STEVENSON, NICHOLAS, SEAMAN
STOCK, H.E., MARINE PRIVATE 
STRONGMAN, JAMES, MARINE PRIVATE 
SUGISAKI, ISA, WARDROOM STEWARD 
SUMAN, E.B., MARINE PRIVATE 
SUTTON, FRANK, FIREMAN, SECOND CLASS 
SUZUKI, KASHITARA, MESS ATTENDANT 
TALBOT, FRANK C., LANDSMAN
     TEACKLE, HARRY, SEAMAN
TEHAN, DANIEL J., COAL PASSER 
THOMPSON, GEORGE, LANDSMAN
     THOMPSON, T.G., MARINE CORPORAL 
         THOMPSON, WILLIAM H., LANDSMAN
TIGGES, FRANK B., COPPERSMITH
TIMPANY, E.B., MARINE PRIVATE 
TINSMAN, WILLIAM H., LANDSMAN
TODORESCO, CONSTANTIN, FIREMAN, FIRST CLASS 
     TOPPIN, DANIEL G., WARDROOM COOK 
TROY, THOMAS, COAL PASSER 
TUOHEY, MARTIN, COAL PASSER 
     TURPIN, JOHN H., MESS ATTENDANT 
VAN HORN, H.A., MARINE PRIVATE 
WAGNER, HENRY, MARINE FIRST SERGEANT 
WALSH, JOSEPH F., COCKSWAIN
WALLACE, JOHN, ORDINARY SEAMAN 
WARREN, ASA V., MARINE PRIVATE 
WARREN, JOHN, FIREMAN, SECOND CLASS 
     WATERS, THOMAS J., LANDSMAN
         WEBBER, MARTIN V., LANDSMAN
WHITE, CHARLES O., CHIEF MASTER- AT - ARMS
     WHITE, JOHN E., LANDSMAN
WHITE, ROBERT, MESS ATTENDANT 
WHITEN, GEORGE, SEAMAN
WICKSTROM, JOHAN E., SEAMAN
WILSON, ALBERT, SEAMAN
WILSON, ROBERT, CHIEF QUARTERMASTER 
     WILBUR, BENJAMIN R., COCKSWAIN
WILBUR, GEORGE W., APPRENTICE, FIRST CLASS 
     WILLIAMS, HENRY, CABIN COOK 
         WILLIAMS JAMES, GUNNER'S MATE, THIRD CLASS 
             WILLIS, ALONZO, APPRENTICE, SECOND CLASS 
WILLS, A.O.MARINE PRIVATE 
ZIEGLER, JOHN H., COAL PASSER `;

str = str = str.replace(/ +(?= )/g, '');

var data = str.split("\n");